src/components/accordion/accordion.tsx, src/components/summary-list/summary-list.tsx
Adds support for nested child arrays for select components that expect children of a particular shape.
```tsx
<Accordion>
<AccordionItem ... />
{list.map(item => <AccordionItem key={item} ... />}
{isTrue ? <AccordionItem ... /> : null}
</Accordion>
```
=> fix(components): Better handling for nested array children

package.json, src/components/accordion/accordion.tsx, src/components/button/button.test.tsx, src/components/button/button.tsx, src/components/center/center.tsx, src/components/checkboxes/checkboxes.tsx, src/components/dialog/styles.scss, src/components/error-summary/error-summary.tsx, src/components/fieldset/fieldset.tsx, src/components/form-group/form-group.tsx, src/components/input/input.tsx, src/components/layout/__snapshots__/layout.test.tsx.snap, src/components/layout/layout.test.tsx, src/components/layout/layout.tsx, src/components/link-box/link-box.tsx, src/components/link/link.tsx, src/components/radios/radios.tsx, src/components/select/__snapshots__/select.spec.tsx.snap, src/components/select/select.spec.tsx, src/components/select/select.tsx, src/components/side-bar/side-bar.tsx, src/components/simple-pagination/__snapshots__/simple-pagination.test.tsx.snap, src/components/simple-pagination/simple-pagination.test.tsx, src/components/simple-pagination/simple-pagination.tsx, src/components/text-area/text-area.tsx, src/types/lbh-frontend.d.ts, yarn.lock
- Make relevant components polymorphic
- Remove back button from Layout component
- Add override (width) to relevant components
Example usage of Polymorphic Components
```tsx
import { Link as RouterLink } from 'react-router-dom';
<Button as="a" href="/">Button Link</Button>
<Link as={RouterLink} to="/">Router Link</Link>
```
Deprecation:
ButtonLink, LinkButton to be removed in favour of Polymorphic Button and Link components.
Actions:
Update MFEs to remove usage of deprecated components and then remove from common.
Update MFE's Layout usage to include back button in `top` prop.
=> feat(comps): make relevant components polymorphic

src/api/axios.test.ts, src/api/axios.ts, src/components/button/__snapshots__/button.test.tsx.snap, src/components/button/button.test.tsx, src/components/button/button.tsx, src/test-utils.tsx
Axios res interceptor will now extract the `Etag` header and append it to the response data `{ etag: '12' }`.
Axios req interceptor will now extract the `etag` data param and append it to the `If-Match` header.
=> feat(api): extract etag from get requests and append if-match on patch

lib/components/layout/__snapshots__/layout.test.tsx.snap, lib/components/layout/layout.test.tsx, lib/components/layout/layout.tsx
I've added an additional prop to the Layout component. This offers us the ability to separate the back link and headers, allowing the user to skip past the back link.
=> feature(TL-175): Adding a backLink prop to Layout

lib/api/comments/v1/service.ts, lib/api/comments/v2/services.ts, lib/api/contact-details/v1/service.ts, lib/api/person/v1/service.ts, lib/api/person/v2/service.ts, lib/api/property/v1/service.ts, lib/api/reference-data/v1/service.ts, lib/api/tenure/v1/service.ts, lib/hooks/index.ts, lib/http/index.ts, lib/http/use-axios-swr.test.ts, lib/http/use-axios-swr.ts
Added missing export in `index.ts` under hooks directory for `useErrorCodes`
=> fix(useErrorCodes): exporting useErrorCodes hook

lib/api/address/v1/service.test.ts, lib/api/address/v1/service.ts
After discussing this we've decided that to retrieve an address via UPRN, we're going to be using the V1 endpoint in SearchAddressController. We have this working in Postman, however the existing service file does not have a call to allow an address to be retrieved via the UPRN (unlike the service in api\address\v2).
I've copied the call from api\address\v2\service, and amended it slightly.
Also corrected spelling mistake in interface name SearchAddressResponse.
=> MR-692 - Add getAddressViaUprn call for Addresses API V1 endpoint

lib/api/asset/v1/service.test.ts, lib/api/asset/v1/service.ts, lib/api/asset/v1/types.ts
- Added patchAsset in asset\v1\service to enable asset patching in mtfh-frontend-property.
- Updated Asset interface with versionNumber property, as the BE returns this. Set this to optional to avoid potential TS issues where Asset is already in use, and set some interfaces to be exported/public for use in tests.
- Added tests for patchAsset and useAsset.
=> MR-692 - Add PatchAsset API call for use in mtfh-frontend-property

lib/api/asset/v1/service.test.ts, lib/api/asset/v1/service.ts
Fixed test after PR #231 - Somehow the failing test was not picked by the pipeline, until the PR was merged into main.
Original PR description:
PatchAsset 
- Set assetAddress type to correct one (EditAssetAddressRequest)
- Added error to be returned on promise rejection#
- Removed then/resolve as not required
Error in mtfh-frontend-property:
=> MR-692 - PatchAsset - Set assetAddress type to correct one (EditAssetAddressRequest) - (retry)

lib/api/asset/v1/service.ts
For some reason after I last edited this, in case of an error, the returned promise would still be returned as fulfilled instead of rejected, meaning the `.catch` in mtfh-frontend-property, would never be called, but instead, despite the error, the `.then` code block would execute regardless.
Not sure why, so I'm setting this code back to when it was working fine/as expected.
=> MR-692 - PatchAsset API call edit

lib/api/address/v1/service.ts
Edited getAddressViaUprn request to return a promise so that in case of errors, the catch block is triggered and the promise is rejected.
I was able to test this manually (in mtfh-frontend-property) and it works as intended:
- address found > `then()` block is executed
- any errors > `catch()` block is executed
=> MR-692 - Address getAddressViaUprn request now returns a promise

lib/api/cautionary-alerts/v1/service.ts
This function is needed in the cautionary-alerts microfrontend in order to implement a process for ending cautionary alerts. 
[Relevant PR on Cautionary Alerts API](https://github.com/LBHackney-IT/cautionary-alerts-api/pull/101)
This is part of work to create a "manage cautionary alerts" page which will have an option for users with elevated access to end alerts.
=> Added endCautionaryAlert function to api/cautionary-alerts

lib/api/asset/v1/service.test.ts, lib/api/asset/v1/service.ts, lib/api/asset/v1/types.ts
Apologies for the many commits, this branch was mostly used for testing a few changes to the createAsset request, specifically to the type of object it receives as a parameter. 
A new interface has been created for CreateNewAssetRequest (rather than using Asset as reference).
This interface only incorporates the fields captured by the New Asset Form in MMH (`{mmh-url}/property/new`)
=> MR-698 - Created CreateNewAssetRequest interface for use when creating a new asset in MMH-Property

lib/api/asset/v1/types.ts
Numeric values in CreateNewAssetRequest  that are not required by New Asset form are now nullable.
This prevents them being converted to 0 and end up being misleading.
Also removed postPreamble from CreateNewAssetRequest as not currently required
=> MR-698 - Numeric values in CreateNewAssetRequest  that are not required by New Asset form are now nullable

lib/api/asset/v1/service.test.ts, lib/api/asset/v1/types.ts
Partial copy of PR #243 which failed to merge due to a build issue (postPreamble property had not been removed in test).
Numeric values in CreateNewAssetRequest that are not required by New Asset form are now nullable.
This prevents them being converted to 0 and end up being misleading.
Also removed postPreamble from CreateNewAssetRequest as not currently required
=> MR-698 - Angelo/create new asset request interface change v2

lib/api/cautionary-alerts/v1/service.ts
When sending through an EndCautionaryAlert API request, an end date should be provided as part of the request data.
=> add end date to endCA API request

lib/api/tenure/v1/service.ts
- The shared axios implementation uses the etag field to set the if-match header - bit of a bizarre way of doing it but there we go
- As this is part of the object itself and is decoded in the shared http.ts library, we don't need to doa ny manual setting of this item
=> Fixup editTenuredAsset call

lib/api/asset/v1/service.test.ts, lib/api/asset/v1/types.ts
With relation to PR: https://github.com/LBHackney-IT/mtfh-frontend-property/pull/74
Added Post Preamble (string) and Patches (nullable) field to CreateNewAssetRequest interface.
The New Asset form will require these two new fields.
=> Added Post Preamble and Patches (nullable) fields to CreateNewAssetRequest interface

lib/api/patch/service.ts, lib/api/patch/v1/service.test.ts, lib/config/config.ts
Following PR https://github.com/LBHackney-IT/patches-and-areas-api/pull/43, the "Add new asset" form within MMH (Property MFE) requires a call to the new GetAllPatchesAndAreas endpoint in Patches & Areas API, to populate the Patch options.
- Updated config.ts file with new entry for Patches & Areas API V1
- Created new service file with call to getAllPatchesAndAreas endpoint
- Created test
**Note: .env file will require a new entry PATCHES_AND_AREAS_API_V1**
=> MR-698 - Add Patches & Areas API call

lib/api/asset/v1/mocks.ts, lib/api/asset/v1/service.test.ts, lib/api/asset/v1/types.ts, lib/api/patch/v1/mocks.ts
Created re-usable and publicly available asset and patch mocks to act as a source of truth for use in tests across the micro-frontends.
Added RentGroup enum as a new attribute for the asset object to match the API response schema.
This will ease the process of updating the schema for asset mocks used for tests in other frontends, including mtfh-frontend-property, and ensures all tests use the same schema.
An alternative could have been to update the schema in mtfh-test-utils but that solidifies the dependency on that package and greatly increases the difficulty of any future schema updates.
Mocks for asset objects and patches and areas were extracted into mock files and used to build up an asset mock, now referenced in the asset tests here.
=> Refactored asset mocks to allow for universal access

lib/api/tenure/v1/service.test.ts, lib/api/tenure/v1/service.ts
Added `paymentReference`field to `TenureParams` interface for use in the Tenure microfrontend. This allows the Edit Tenure form to include the field
The field will remain disabled on the tenure MFE pending further refinement but still needs this change to the schema in preparation.
Used by the new functionality in the [Tenure MFE PR 100](https://github.com/LBHackney-IT/mtfh-frontend-tenure/pull/100)
=> POH-104 - Add paymentReference to TenureParams

lib/api/asset/v1/types.ts
CreateNewAssetRequest assetLocation.parentAssets type was set to `any`. Changed to specific, correct type `ParentAsset[]`.
=> CreateNewAssetRequest assetLocation.parentAssets type set from "any" to specific type

lib/api/asset/v1/service.test.ts, lib/api/asset/v1/service.ts
- Add validation to CreateNewAsset API call to ensure only one parent asset is in the payload
- Tested manually in New Asset form by hardcoding 2 parents in assetLocation.parentAsset and it works
- Added test
Related to PR: https://github.com/LBHackney-IT/mtfh-frontend-property/pull/102
=> MR-734 - Add validation to CreateNewAsset API call to ensure only one parent asset is in the payload

lib/api/asset/v1/service.ts
[https://hackney.atlassian.net/browse/MR-743?atlOrigin=eyJpIjoiYWNkNzVlYjA5Y2JjNGUxNWJmMzAyNzhmMWFlYTY3OGQiLCJwIjoiaiJ9](https://hackney.atlassian.net/browse/MR-743?atlOrigin=eyJpIjoiYWNkNzVlYjA5Y2JjNGUxNWJmMzAyNzhmMWFlYTY3OGQiLCJwIjoiaiJ9)
- The default pageSize for child assets in the housingSearchAPI is 12. However, many properties have multiple hundred. I have increased the default value to 5000, which is way too high, because that will ensure all childAssets are fetched in a request
- Add getChildAssets endpoint - might be useful
=> UseChildAssets - Increase default pageSize

lib/api/asset/v1/mocks.ts, lib/api/asset/v1/service.test.ts, lib/api/asset/v1/service.ts, lib/api/asset/v1/types.ts
Prior to merging this PR/as of now, `patchAsset` is only set up for editing the `boilerHouseId` of an asset (I have checked the other repos to make sure there are no other MFE referencing this method, other than Common and Property - [Github references](https://github.com/search?q=org%3ALBHackney-IT%20patchasset&type=code))
This PR enables patchAsset to accept a new type of request, to change asset ownership (`isCouncilProperty` field).
Changes:
- Renamed `PatchAssetRequest` interface to `PatchAssetBoilerHouseRequest`, more specific. 
- Added `PatchAssetLbhOwnershipRequest` interface, to be used when editing asset ownership.
- Updated AssetManagement interface to be aligned with its [counterpart class in Asset Shared](https://github.com/LBHackney-IT/asset-shared/blob/main/Hackney.Shared.As …
=> MR-757 - Add API request to change Asset Management (required for LBH Ownership edit feature)

lib/api/patch/v1/mocks.ts, lib/api/patch/v1/service.test.ts, lib/api/patch/v1/service.ts, lib/api/patch/v1/types.ts
Note: A responsible entity refers to a housing officer or housing area manager responsible for a patch or an area (collection of patches)
This adds support for these endpoints of the Patches and Areas API:
1. `addResponsibleEntityToPatch`
PATCH /patch/${patchId}/responsibleEntity/${responsibleEntityId}
Adds a responsible entity to the list of responsible entities for a patch/area
2. `deletePatchesAndAreasResponsibilities`
DELETE /patch/${patchId}/responsibleEntity/${responsibleEntityId}
Removes a responsible entity from the list of responsible entities for a patch/area
3. `replacePatchResponsibleEntities`
PUT /patch/${patchId}/responsibleEntities`
Replaces the current list of a patch or area's responsible entities with a new list with all relevant data needed …
=> Add patches and areas API endpoints (delete responsibleEntitity, append responsibleEntity, replace responsibleEntities)

lib/api/patch/v1/service.test.ts, lib/api/patch/v1/service.ts
Returning a promise adds unnecessary complexity
=> get patch or area synchronously

lib/api/asset/v1/types.ts
Change asset patches schema
Should be merged AFTER a data migration script completes to remove asset.patches[] and set patchId and areaId fields on the database
=> Change asset patch schema

lib/api/asset/v1/mocks.ts, lib/api/asset/v1/types.ts
- Add a `rentGroup` field to the `CreateNewAssetRequest`.
- Convert the `RentGroup` enum from numeric enum to string enum.
- Make the `rentGroup` field optional within the `Asset` model.
- This field is needed for capturing the optional Rent Group information upon Asset's creation. Read more details on the linked pull request for `mtfh-microfrontend-property` repository [TODO: link the soon to come PR once created].
- Made the `RentGroup` enum a string enum to avoid unintended behaviours during its type conversions going forward.
- Not all assets are meant to have `rentGroup` information, so it makes sense to explicitly reflect that within the model.
- I don't think the `rentGroup` field or the `RentGroup` enum type has been used anywhere yet. It has merely been put in place as a …
=> Add an optional `rentGroup` field to the `CreateNewAssetRequest` model.

lib/api/asset/v1/types.ts
- Add full descriptions of the "Rent Group" codes.
- The user feedback has suggested that not everyone using the "New Property" form is familiar with the Rent Group codes listed. Which raises a good point that wherever the Rent Group enum may be used, having access to full descriptions of the codes is of high value.
- This PR should be viewed as an add-on to the PR #290 , where the numeric enum was changed to a string enum. This time we're keeping it as a string enum, but expanding on the description value.
- This work relates to the Jira ticket: [HPT-48](https://hackney.atlassian.net/browse/HPT-48).
[HPT-48]: https://hackney.atlassian.net/browse/HPT-48?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add "RentGroup" code descriptions.

lib/api/asset/v1/types.ts
- A typo fix for the '`RentGroup`' enum '`TAG`' key description.
- Extends the PR #291
=> Fix the 'RentGroup' enum 'TAG' key description typo.

lib/api/tenure/v1/types.ts
https://hackney.atlassian.net/browse/TS-1362?atlOrigin=eyJpIjoiZjY1MmM0ZDJjZTc2NDk3ZGJiZWJhMDUxNmJkMmQxMGUiLCJwIjoiaiJ9 
**What** 
Updates the Tenure type object.
**Why**
We are trying where possible to use functionality that already exists in common. Currently, we replicate some elements of the hooks and services in the TA application. For consistency, testing and minimising replication we want to reduce this.
In order to use the Tenure features from common, the typings need to be updated to match the response. Some types are missing, and others appear to not be in use.
I'm not sure how widely used/where else this api is used. So would be good to get some ideas on where else the change might need to be tested out. 
**How**
This updates tenure/v1/types object.
=> Updates Tenure typings

lib/api/tenure/v1/types.ts
**Adds optional to isTemporaryAccomodation prop**
https://hackney.atlassian.net/browse/TS-1362?atlOrigin=eyJpIjoiZjY1MmM0ZDJjZTc2NDk3ZGJiZWJhMDUxNmJkMmQxMGUiLCJwIjoiaiJ9
What
Updates the Tenure type object.
Why
We are trying where possible to use functionality that already exists in common. Currently, we replicate some elements of the hooks and services in the TA application. For consistency, testing and minimising replication we want to reduce this.
In order to use the Tenure features from common, the typings need to be updated to match the response. Some types are missing, and others appear to not be in use.
I'm not sure how widely used/where else this api is used. So would be good to get some ideas on where else the change might need to be tested out.
How
This updates tenure/v1/types …
=> corrects personTenureType to be optional prop

lib/api/tenure/v1/service.test.ts, lib/api/tenure/v1/service.ts, lib/api/tenure/v1/types.ts
[TS-1322](https://hackney.atlassian.net/browse/TS-1322) As a user - I want to be able to change the status of a booking - So that other officers in charge can pick it up and take the right actions.
Added `TemporaryAccommodationInfo` as an optional attribute to the `Tenure` data type and the `EditTenureParams` which is part of enabling the frontends to fetch and edit these attributes via the Tenure API.
See also: corresponding [Tenure API PR](https://github.com/LBHackney-IT/tenure-shared/pull/28)
This is needed so that the Temporary Accommodation frontend can allow users to view, filter by, and edit these attributes.
[TS-1322]: https://hackney.atlassian.net/browse/TS-1322?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> Add tempAccInfo to tenure

lib/api/tenure/v1/service.test.ts, lib/api/tenure/v1/service.ts, lib/api/tenure/v1/types.ts
This corresponds with this [Tenure API Change](https://github.com/LBHackney-IT/tenure-shared/pull/29) and re-aligns the schemas
Property was renamed to avoid confusion with "temporary account"
=> Rename tempAccInfo to tempAccommodationInfo

lib/api/tenure/v1/types.ts
This is to give clients the flexibility to send it as null in case there is no valid value to provide in requests to the tenure API
=> Make booking status nullable

lib/api/tenure/v1/types.ts
This will allow sending through undefined in case there is no officer to be sent by the client
=> Optional assigned officer

lib/api/tenure/v1/service.test.ts
Ref https://github.com/LBHackney-IT/mtfh-frontend-common/pull/300 - test wasn't updated and failed in pipeline.
https://hackney.atlassian.net/browse/TS-1410?atlOrigin=eyJpIjoiMjBlNGQwNjcyMTAzNGMwOTk3ODM1ZGM0MDk4YjU5ODUiLCJwIjoiaiJ9
What
Adds ID to TemporaryAccommodationOfficer and makes ID and email option fields.
Why
It matches the API and allows an ID to be stored against the officer. Email will be left for possible future implementation.
=> Updates test to cover assigned officer change

lib/api/tenure/v1/service.test.ts, lib/api/tenure/v1/service.ts, lib/api/tenure/v1/types.ts
**What**
Adds new TenureRefusedDate to the types, test and editTenure method
**Why**
We're using this field for TA officers to record a rejection of accommodation.
=> Updates types and methods to allow for new FurtherAccountInformation

lib/api/address/v1/service.test.ts, lib/api/address/v1/service.ts, lib/api/address/v1/types.ts
This update adds support for the new structure query string parameter recently added to the address search API.
Address search V1 service has been updated to pass the `Structure` parameter to the API when requested. The service is not opinionated in terms of the value and simple passes the provided value as is.
`Address` type has also been updated to include `childAddresses` property which is now available in the address results.
=> TS-1639 add sctructure query support for address search

lib/api/address/v1/service.test.ts, lib/api/address/v1/service.ts
Update `getAddressViaUprn` function in address v1 service to support searching by parent UPRN.
In some use cases we need to be able to search for addresses by their parent UPRN. This is required to support Temporary Accommodation block feature for example
Add optional `isParentUPRN` parameter to `getAddressViaUprn` function. If set to true `parentUprn` is used in the query string instead of the deualt `uprn`.
=> TS-1963 Add support for searching by parent uprn

lib/api/address/v1/service.test.ts, lib/api/address/v1/service.ts
Update `getAddressViaUprn ` to support `page` and `pageSize` query string parameters to support paging.
In Addresses API the default page size is set to 50, so we only ever get maximum of 50 addresses without the ability to use paging. In Temporary Accommodation we need to be able to fetch all addresses with a given parent UPRN to support block functionality.
Update `getAddressViaUprn` , so that clients can pass page and pageSize to achieve paging. Parameters are optional and are omitted altogether from the query string if values are not provided.
=> TS-1963 Add paging support to getAddressViaUprn

lib/api/address/v1/service.test.ts, lib/api/address/v1/service.ts
Add optional `pageCount` and `totalCount` properties to the `SearchAddressResponse`, so clients can use the paging provided by the Addresses API. This was accidentally left out in the previous paging update PR. 
Also exports the `SearchAddressResponse`, so it can be used in tests etc. in other MFEs.
=> TS-1987 Add paging properties to search address response

.circleci/config.yml, terraform/pre-production/aws_ssm_parameter.tf, terraform/pre-production/main.tf, terraform/pre-production/variables.tf
[TS-2072](https://hackney.atlassian.net/browse/TS-2072)
This update adds pre-production resources and workflows.
New Terrraform `terraform-init-then-plan` command has been added, so it's possible to see terraform changes before appkying them. This has only been added to the new pre-production workflow.
Please note e2e test setup hasn't been added for pre-production. This is just the initial config to get the CloudFront distribution in place with the latest code.
Also adds all SSM parameter dependencies that haven't been added to the account yet.
[TS-2072]: https://hackney.atlassian.net/browse/TS-2072?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> TS-2072 add pre-production workflows
