LBHackney-IT/mtfh-frontend-common

- src/components/layout/styles.scss
- src/components/side-bar/__snapshots__/side-bar.test.tsx.snap
- src/components/side-bar/side-bar.test.tsx
- src/components/side-bar/side-bar.tsx
- src/components/side-bar/styles.scss
- src/components/summary-list/__snapshots__/summary-list.test.tsx.snap
- src/components/summary-list/index.ts
- src/components/summary-list/summary-list.test.tsx
- src/components/summary-list/summary-list.tsx
- src/utils/index.ts
- src/utils/pluralize.ts
- src/utils/tests/width-overrides.test.ts
- src/utils/width-overrides.ts
Add SummaryList and SummaryListItem components.
Refactor SideBar Component to a forwardable ref component.
> feat(components): add summary-list

- src/components/accordion/accordion.tsx
- src/components/error-summary/error-summary.tsx
- src/components/fieldset/__snapshots__/fieldset.test.tsx.snap
- src/components/fieldset/fieldset.test.tsx
- src/components/number-input/number-input.test.tsx
- src/components/radios/radios.tsx
- src/components/side-bar/__snapshots__/side-bar.test.tsx.snap
- src/components/side-bar/side-bar.test.tsx
- src/components/side-bar/side-bar.tsx
- src/components/summary-list/summary-list.tsx
Allow null type children in components that expect child ReactElements.
> fix(components): allow nullable children

- .eslintrc
- package.json
- src/components/date-input/__snapshots__/date-input.test.tsx.snap
- src/components/date-input/date-input.tsx
- src/components/date-input/styles.scss
- src/components/field/field.test.tsx
- src/components/field/field.tsx
- src/components/field/index.ts
- src/components/form-group/form-group.tsx
- src/components/form-group/styles.scss
- src/components/index.ts
- src/components/summary-list/styles.scss
- src/components/summary-list/summary-list.tsx
- src/configuration/configuration.test.ts
- src/configuration/configuration.ts
- webpack.config.js
- yarn.lock
Add `formik` components to common
> feat(components): add formik components

- src/hooks/index.ts
- src/hooks/tests/use-feature-toggle.test.ts
- src/hooks/use-feature-toggle.ts
adds `useFeatureToggle` react hook.
```ts
const toggle = useFeatureToggle('MMH.SearchProperty');
```
> feat(feature-toggle): add useFeatureToggle hook

- lib/components/index.ts
- lib/components/stepper/__snapshots__/stepper.test.tsx.snap
- lib/components/stepper/index.ts
- lib/components/stepper/step.tsx
- lib/components/stepper/stepper.test.tsx
- lib/components/stepper/stepper.tsx
- lib/components/stepper/styles.scss
- lib/locale.ts
> feat(stepper): adds basic stepper

- lib/components/index.ts
- lib/components/text/__snapshots__/text.test.tsx.snap
- lib/components/text/index.ts
- lib/components/text/styles.scss
- lib/components/text/text.test.tsx
- lib/components/text/text.tsx
Adds Text component:
```tsx
<Text>Hello</Text>
<Text as="span">Inline Hello</Text>
<Text as="strong">strong Bold</Text> / <Text variant="bold">p Bold</Text>
<Text size="lg">Large Text</Text>
```
> feat(components): add text component

- lib/components/text/__snapshots__/text.test.tsx.snap
- lib/components/text/text.tsx
> fix(components): set default size for text component

- lib/configuration/configuration.ts
As per https://slack-files.com/T02D15XMM-F02GQKR6YMN-0fef1885ce
Also see PR on the configuration API https://github.com/LBHackney-IT/configuration-api-files/pull/68
> Define Repairs Hub feature toggles

- terraform/development/main.tf
- terraform/production/main.tf
- terraform/staging/main.tf
Update cors rule to allow requests from hfs system.
> S3 CORS Update

- terraform/development/main.tf
> add maa url

- terraform/development/main.tf
- added url in development to pass cors
> add url for cors

- terraform/staging/main.tf
> add maa staging

- lib/api/asset/v1/service.ts
- lib/api/asset/v1/types.ts
Added EditAssetAddressRequest interface to use when patching an asset
> MR-692 - Added EditAssetAddressRequest interface to use when patching an asset

- lib/api/address/v1/service.test.ts
- lib/api/asset/v1/service.test.ts
- lib/api/contact-details/v1/service.test.ts
- lib/api/contact-details/v2/service.test.ts
- lib/api/contact-details/v2/utils/split-contact-details.test.ts
- lib/api/person/v1/utils/sort-tenures-by-active/sort-tenures-by-active.spec.ts
- lib/api/tenure/v1/service.test.ts
- Rename all test descriptions using a valid testing methodology (e.g. If / When / Then)
> [Tech Debt] Format test names

- .circleci/config.yml
- webpack.config.js
Updated env variable settings following PR: https://github.com/LBHackney-IT/mtfh-frontend-common/pull/252
> MR-698 - Updated env variables following previous PR (#252)

- lib/api/patch/v1/index.ts
- lib/api/patch/v1/service.test.ts
- lib/api/patch/v1/service.ts
Moved service file into v1 folder. 
Updated import/exports.
> MR-698 - Moved service file into v1 folder. Added export to index file for service file. Updated import in service.test

- lib/api/housing-finance-interim-api/service.ts
API method now returns a promise
> Update updateAddressDetails method

- lib/api/address/v1/service.test.ts
- lib/api/asset/v1/service.test.ts
- lib/api/cautionary-alerts/v1/service.test.ts
- lib/api/contact-details/v1/service.test.ts
- lib/api/contact-details/v2/service.test.ts
- lib/api/housing-finance-interim-api/service.test.ts
- lib/api/patch/v1/service.test.ts
- lib/api/tenure/v1/service.test.ts
- lib/api/work-order/v2/service.test.ts
Item in 44 in [MTFH Tech Debt Register](https://docs.google.com/spreadsheets/d/1TUS7XjtLX6cpdN_r4Spg2Lw12B4921q004eJKCEJCHQ/edit#gid=0)
Issue: API tests in mtfh-frontend-common have descriptions that are not in the usual/correct format. 
Suggested fix: Rename all test descriptions using a valid testing methodology (e.g. If / When / Then)
> Tech Debt - Amend test names

- README.md
This should to (hopefully) prompt anyone making changes to this repository to create tests when adding new features or making changes, and most importantly check that that the `mtfh-tl-e2e-tests` pipeline runs successfully after such changes are merged into the `main` branch.
> Updated readme with note on e2e tests

- lib/api/asset/v1/mocks.ts
- lib/api/asset/v1/types.ts
> Add flag for SOR addition to CreateAssetRequest

- lib/api/patch/v1/service.test.ts
- lib/api/patch/v1/service.ts
Add new `getPatchOrAreaById` function to the patches and areas service
> Update patch api

- lib/api/asset/v1/mocks.ts
Quick fix - missed out an areaId and patchId from a mock
> add PatchId and AreaId to mock

- lib/api/tenure/v1/types.ts
https://hackney.atlassian.net/browse/TS-1410?atlOrigin=eyJpIjoiMjBlNGQwNjcyMTAzNGMwOTk3ODM1ZGM0MDk4YjU5ODUiLCJwIjoiaiJ9
**What**
Adds ID to TemporaryAccommodationOfficer and makes ID and email option fields. 
**Why**
It matches the API and allows an ID to be stored against the officer. Email will be left for possible future implementation.
> Updates types for TA officer

- lib/api/tenure/v1/service.ts
https://hackney.atlassian.net/browse/TS-1864?atlOrigin=eyJpIjoiZDA2N2EyMjhhOTAyNDFiNzk5Mzk1MGUzYWI3OTdlZGYiLCJwIjoiaiJ9
What:
Adds a new optional type needed for the EditTenureParams.
> Updates the tenure edit params

- lib/api/asset/v1/mocks.ts
- lib/api/asset/v1/service.test.ts
- lib/api/asset/v1/service.ts
- lib/api/asset/v1/types.ts
- lib/api/patch/v1/service.test.ts
- lib/api/patch/v1/service.ts
- package.json
Get by patch name API call and UpdatePropertyPatch API call with tests
> Update property patch
